engine:
  max-fps: 60
  max-control-refresh: 100
window:
  width: 800
  height: 600
  fullscreen: false
control:
  rotation-speed: 0.25
  movement-speed: 0.05
  zoom-speed: 0.005
matrix:
  field-of-view-angle: 50.0
  distance-to-near-clipping-plane: 1.0
  distance-to-far-clipping-plane: 100.0