engine:
  max-fps: 30
  max-control-refresh: 100
window:
  width: 600
  height: 600
  fullscreen: false
  invert-y: true
control:
  movement-speed: 0.05
  k-factor-change-speed: 0.005
  i-factor-change-speed: 0.005
  n-factor-change-speed: 0.05
  c-factor-change-speed: 0.05